/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaspkg;

import java.awt.Color;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import server.Usuario;

public class Cliente extends javax.swing.JFrame {

    public Usuario cliente = new Usuario();
    public Socket socketCliente;
    public String chat = "G";
    public Socket socket;
    public PrintStream out;
    public BufferedReader in;
    public JTabbedPane pane;

    /**
     * Creates new form Inicio
     */
    public Cliente() {
        initComponents();
        pane = TabbedPane;
        pane.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        IpLabel = new javax.swing.JLabel();
        IpTextField = new javax.swing.JTextField();
        PortaTextField = new javax.swing.JTextField();
        NomeLabel = new javax.swing.JLabel();
        NomeTextField = new javax.swing.JTextField();
        MaterialLabel = new javax.swing.JLabel();
        MaterialComboBox = new javax.swing.JComboBox<>();
        DescricaoLabel = new javax.swing.JLabel();
        DescricaoScrollPane = new javax.swing.JScrollPane();
        DescricaoTextPane = new javax.swing.JTextPane();
        PortaLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ColetorRadioButton = new javax.swing.JRadioButton();
        DoadorRadioButton = new javax.swing.JRadioButton();
        ConectarButton = new javax.swing.JButton();
        jButtonDesconectar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaClients = new javax.swing.JTable();
        ChatPrivadoBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        ChatTextField = new javax.swing.JTextField();
        ChatSendBtn = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChatTextPaneGeral = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatTextPaneMaterial = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        ChatTextPanePrivado = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        IpLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IpLabel.setText("IP:");
        IpLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        IpLabel.setMaximumSize(new java.awt.Dimension(50, 15));
        IpLabel.setMinimumSize(new java.awt.Dimension(50, 15));
        IpLabel.setPreferredSize(new java.awt.Dimension(15, 15));

        IpTextField.setText("127.0.0.1");
        IpTextField.setMaximumSize(new java.awt.Dimension(150, 20));
        IpTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        IpTextField.setPreferredSize(new java.awt.Dimension(150, 20));
        IpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpTextFieldActionPerformed(evt);
            }
        });

        PortaTextField.setText("1234");
        PortaTextField.setMaximumSize(new java.awt.Dimension(50, 20));
        PortaTextField.setMinimumSize(new java.awt.Dimension(20, 20));
        PortaTextField.setPreferredSize(new java.awt.Dimension(50, 20));

        NomeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NomeLabel.setText("Nome:");
        NomeLabel.setPreferredSize(new java.awt.Dimension(46, 15));

        NomeTextField.setText("Teste");

        MaterialLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaterialLabel.setText("Material:");

        MaterialComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "oleo", "metal", "roupa", "papel", "plastico", "eletronico" }));
        MaterialComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialComboBoxActionPerformed(evt);
            }
        });

        DescricaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DescricaoLabel.setText("Descrição:");

        DescricaoTextPane.setEnabled(false);
        DescricaoTextPane.setMinimumSize(new java.awt.Dimension(300, 200));
        DescricaoTextPane.setPreferredSize(new java.awt.Dimension(300, 200));
        DescricaoScrollPane.setViewportView(DescricaoTextPane);

        PortaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PortaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PortaLabel.setText("Porta:");
        PortaLabel.setMaximumSize(new java.awt.Dimension(50, 15));
        PortaLabel.setMinimumSize(new java.awt.Dimension(50, 15));
        PortaLabel.setPreferredSize(new java.awt.Dimension(46, 15));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        buttonGroup1.add(ColetorRadioButton);
        ColetorRadioButton.setSelected(true);
        ColetorRadioButton.setText("Coletor");
        ColetorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColetorRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ColetorRadioButton);

        buttonGroup1.add(DoadorRadioButton);
        DoadorRadioButton.setText("Doador");
        DoadorRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DoadorRadioButtonStateChanged(evt);
            }
        });
        DoadorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoadorRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoadorRadioButton);

        ConectarButton.setText("Conectar");
        ConectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarButtonActionPerformed(evt);
            }
        });

        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.setEnabled(false);
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescricaoScrollPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PortaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PortaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaterialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaterialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DescricaoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ConectarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDesconectar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PortaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PortaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaterialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaterialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescricaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescricaoScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConectarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários Conectados"));
        jPanel5.setAutoscrolls(true);

        TabelaClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Material", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TabelaClients);

        ChatPrivadoBtn.setText("Conversa Privada");
        ChatPrivadoBtn.setEnabled(false);
        ChatPrivadoBtn.setFocusPainted(false);
        ChatPrivadoBtn.setFocusable(false);
        ChatPrivadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatPrivadoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChatPrivadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChatPrivadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat"));

        ChatTextField.setEnabled(false);
        ChatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatTextFieldActionPerformed(evt);
            }
        });

        ChatSendBtn.setText("Enviar");
        ChatSendBtn.setEnabled(false);
        ChatSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatSendBtnActionPerformed(evt);
            }
        });

        ChatTextPaneGeral.setEditable(false);
        jScrollPane2.setViewportView(ChatTextPaneGeral);

        TabbedPane.addTab("Chat Geral", jScrollPane2);

        ChatTextPaneMaterial.setEditable(false);
        jScrollPane1.setViewportView(ChatTextPaneMaterial);

        TabbedPane.addTab("Chat Material", jScrollPane1);

        jScrollPane4.setEnabled(false);

        ChatTextPanePrivado.setEditable(false);
        jScrollPane4.setViewportView(ChatTextPanePrivado);

        TabbedPane.addTab("Chat Privado", jScrollPane4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(TabbedPane)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ChatTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChatSendBtn)))
                .addGap(3, 3, 3))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChatSendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarButtonActionPerformed
        JSONObject validacao = validaInsercao();
        if (validacao.getBoolean("success")) {
            JSONObject user = criaUser("connect");
            String req = user.toString();
            iniciaConexao(req);
        } else {
            JOptionPane.showMessageDialog(null, validacao.getString("message"), "ERRO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ConectarButtonActionPerformed

    private void DoadorRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DoadorRadioButtonStateChanged

    }//GEN-LAST:event_DoadorRadioButtonStateChanged

    private void DoadorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoadorRadioButtonActionPerformed
        if (DoadorRadioButton.isEnabled()) {
            DescricaoTextPane.setEnabled(true);
        }
    }//GEN-LAST:event_DoadorRadioButtonActionPerformed

    private void ColetorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColetorRadioButtonActionPerformed
        if (ColetorRadioButton.isEnabled()) {
            DescricaoTextPane.setText(null);
            DescricaoTextPane.setEnabled(false);
        }
    }//GEN-LAST:event_ColetorRadioButtonActionPerformed

    private void IpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpTextFieldActionPerformed

    private void MaterialComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialComboBoxActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        //JOptionPane.showConfirmDialog(null, "Desconectado com sucesso!", "Desconectado", JOptionPane.DEFAULT_OPTION);
        int opt = JOptionPane.OK_OPTION;
        Object[] options = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, "Você deseja se desconectar?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcao == JOptionPane.NO_OPTION) {
            opt = JOptionPane.NO_OPTION;
        }
        int opcao1 = JOptionPane.showOptionDialog(null, "Tem certeza?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if (opcao1 == opt) {
            desconectaCliente(socketCliente);
            socketCliente = null;
            DefaultTableModel model = (DefaultTableModel) TabelaClients.getModel();
            model.setRowCount(0);
            ConectarButton.setEnabled(true);
            jButtonDesconectar.setEnabled(false);
            try {
                out.close();
                in.close();
                socket.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    private void ChatPrivadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatPrivadoBtnActionPerformed
//        chat = "P";
//        try {
//            int column = 0;
//            int row = TabelaClients.getSelectedRow();
//            String porta = TabelaClients.getModel().getValueAt(row, column).toString();
//            JSONObject jsonPrivado = new JSONObject();
//            jsonPrivado.put("action", "chat_request_server");
//            jsonPrivado.put("destinatario", porta.toString());
//            out.println(jsonPrivado.toString());
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Selecione um usuário na tabela primeiro.");
//        }
    }//GEN-LAST:event_ChatPrivadoBtnActionPerformed

    private void ChatSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatSendBtnActionPerformed
        if (!ChatTextField.getText().trim().equals("")) {
            enviaMensagem();
            ChatTextField.setText("");
        } else {
            ChatTextField.setText("");
        }
    }//GEN-LAST:event_ChatSendBtnActionPerformed

    private void ChatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatTextFieldActionPerformed
        if (!ChatTextField.getText().trim().equals("")) {
            enviaMensagem();
            ChatTextField.setText("");
        } else {
            ChatTextField.setText("");
        }
    }//GEN-LAST:event_ChatTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });

    }

    private void detectaTipo() {
        if (chat == "G") {
            broadcast();
        } else if (chat == "D") {

        }
    }

    private void enviaMensagem() {
        int selectedIndex = pane.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                chat = "G";
                break;
            case 1:
                chat = "M";
                break;
        }
        JSONObject jsonMensagem = new JSONObject();
        String msg = ChatTextField.getText();
        jsonMensagem.put("mensagem", msg);
        switch (chat) {
            case "G":
                jsonMensagem.put("action", "chat_general_server");
                out.println(jsonMensagem.toString());
                break;
            case "M":
                jsonMensagem.put("action", "chat_room_server");
                out.println(jsonMensagem.toString());
                break;
            case "P":
                jsonMensagem.put("action", "chat_request_server");
                System.out.println("Chat Privado - ainda não implementado");
                break;
            default:
                System.out.println("Nenhum");
        }
        System.out.println("Enviado:" + jsonMensagem);
    }

    private void broadcast() {
        String msg = ChatTextField.getText();
        ChatTextField.setText("");
        JSONObject jsonBroad = new JSONObject();
        jsonBroad.put("action", "chat_general_server");
        jsonBroad.put("mensagem", msg);
        out.println(jsonBroad.toString());
    }

    private void iniciaConexao(String req) {
        System.out.println("Enviado: " + req );
        String ip = IpTextField.getText();
        Integer porta = new Integer(PortaTextField.getText());
        try {
            socket = new Socket(ip, porta);
            out = new PrintStream(socket.getOutputStream());
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            this.socketCliente = socket;
            BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));

            out.println(req);

            ativaConexao();
            if (DoadorRadioButton.isEnabled()) {
                DescricaoTextPane.setEnabled(false);
            }

            new Thread() {
                @Override
                public void run() {
                    mensagemLog("Contectou a " + IpTextField.getText() + ":" + PortaTextField.getText());
                    try {
                        String userInput;
                        while (((userInput = in.readLine()) != null) || socketCliente != null) {
                            try {
                                JSONObject json = new JSONObject(userInput);
                                iniciaAcao(json);
                            } catch (JSONException ex) {
                                desativaConexao();
                                desconectaCliente(socket);
                                errorLog("", 0, ex.getMessage());
                                out.close();
                                in.close();
                                socket.close();
                            }
                        }
                        desativaConexao();
                        desconectaCliente(socket);
                        errorLog("Falha na conexão com o servidor.", 0, "");
                        out.close();
                        in.close();
                        socket.close();
                        //stdIn.close();
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Você foi desconectado");
                        desativaConexao();
                        errorLog("Falha na conexão com o servidor.", 0, ex.getMessage());
                        DefaultTableModel model = (DefaultTableModel) TabelaClients.getModel();
                        model.setRowCount(0);
                    }
                }
            }.start();

        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(null, "Não é possível encontrar o servidor " + ip + e);
            mensagemErro("Não é possível encontrar o servidor " + ip + "\n" + e);
        } catch (ConnectException e) {
            mensagemErro("Não é possível conectar a " + ip + ":" + porta);
        } catch (IOException e) {
            mensagemErro("Erro com o IP " + ip + "\n" + e);
        }
    }

    public void ativaConexao() {
        chat = "G";
        jButtonDesconectar.setEnabled(true);
        ChatTextField.setEnabled(true);
        ChatSendBtn.setEnabled(true);
        ChatPrivadoBtn.setEnabled(true);
        ChatTextPaneMaterial.setText("");
        ChatTextPaneGeral.setText("");
        ConectarButton.setEnabled(false);
        IpTextField.setEnabled(false);
        PortaTextField.setEnabled(false);
        NomeTextField.setEnabled(false);
        MaterialComboBox.setEnabled(false);
        ColetorRadioButton.setEnabled(false);
        DoadorRadioButton.setEnabled(false);
    }

    public void desativaConexao() {
        chat = "G";
        jButtonDesconectar.setEnabled(false);
        ConectarButton.setEnabled(true);
        ChatTextPaneMaterial.setText("");
        ChatTextPaneGeral.setText("");
        ChatTextField.setEnabled(false);
        ChatSendBtn.setEnabled(false);
        ChatPrivadoBtn.setEnabled(false);
        IpTextField.setEnabled(true);
        PortaTextField.setEnabled(true);
        NomeTextField.setEnabled(true);
        MaterialComboBox.setEnabled(true);
        ColetorRadioButton.setEnabled(true);
        DoadorRadioButton.setEnabled(true);
    }

    public void addTexto(JTextPane textPane, String frase, Color cor) {
        StyledDocument doc = textPane.getStyledDocument();
        Style style = textPane.addStyle("I'm a Style", null);

        try {
            StyleConstants.setForeground(style, cor);
            doc.insertString(doc.getLength(), frase + "\n", style);
            textPane.setCaretPosition(textPane.getDocument().getLength());
        } catch (Exception e) {
            textPane.setText(textPane.getText() + frase);
        }
    }

    private void mensagemLog(String mensagem) {
        addTexto(ChatTextPaneGeral, mensagem, Color.DARK_GRAY);
    }

    private void mensagemGeral(String mensagem) {
        addTexto(ChatTextPaneGeral, mensagem, Color.BLUE);
    }

    private void mensagemMaterial(String mensagem) {
        addTexto(ChatTextPaneMaterial, mensagem, Color.GREEN.darker().darker());
        addTexto(ChatTextPaneGeral, mensagem, Color.GREEN.darker().darker());
    }

    private void mensagemErro(String mensagem) {
        addTexto(ChatTextPaneMaterial, "ERRO - " + mensagem, Color.RED);
        addTexto(ChatTextPaneGeral, "ERRO - " + mensagem, Color.RED);
    }

    private JSONObject criaUser(String action) {
        JSONObject user = new JSONObject();
        user.put("action", action);
        user.put("nome", NomeTextField.getText());
        user.put("material", MaterialComboBox.getSelectedItem().toString());
        if (DoadorRadioButton.isSelected()) {
            user.put("tipo", "D");
            user.put("descricao", DescricaoTextPane.getText());
        } else {
            user.put("tipo", "C");
        }

        return user;
    }

    private JSONObject validaInsercao() {
        String message = "";
        JSONObject validacao = new JSONObject();
        validacao.put("success", true);
        if (IpTextField.getText().trim().length() == 0) {
            message += "O Campo IP é Obrigatório.\n";
            validacao.put("success", false);
        }

        if (PortaTextField.getText().trim().length() == 0) {
            message += "O Campo Porta é Obrigatório.\n";
            validacao.put("success", false);
        }

        if (NomeTextField.getText().trim().length() == 0) {
            message += "O Campo Nome é Obrigatório.\n";
            validacao.put("success", false);
        }

        if (MaterialComboBox.getSelectedItem().toString() == "Selecione...") {
            message += "É obrigatório selecionar um material.\n";
            validacao.put("success", false);
        }

        if (!DoadorRadioButton.isSelected() && !ColetorRadioButton.isSelected()) {
            message += "É obrigatório selecionar um tipo.\n";
            validacao.put("success", false);
        }

        if (DoadorRadioButton.isSelected()) {
            if (DescricaoTextPane.getText().trim().length() == 0) {
                message += "Doador precisa informar uma descrição.\n";
                validacao.put("success", false);
            }
        }

        validacao.put("message", message);
        return validacao;
    }

    private void iniciaAcao(JSONObject json) {
        System.out.println("Recebido: " + json);
        if (json.has("action")) {
            if (json.get("action").equals("client_list")) {
                listaClientes(json);
            } else if (json.get("action").equals("chat_general_client")) {
                chat_general_server(json);
            } else if (json.get("action").equals("chat_room_client")) {
                chat_room_client(json);
            } else if (json.get("action").equals("request_error")) {
                JOptionPane.showMessageDialog(null, "Erro na requisição.");
            } else {
                System.out.println("A ação " + json.get("action") + " não existe.");
            }
        } else {
            System.out.println("A chave action não existe.");
        }
    }

    private void chat_room_client(JSONObject json) {
        mensagemMaterial(json.getString("mensagem"));
    }

    private void chat_general_server(JSONObject json) {
        mensagemGeral(json.getString("mensagem"));
    }
    
    private void errorLog(String frase, int porta, String erro) {
        Color cor = null;
        String str = null;
        if (frase.equals("") && porta == 0 && erro.equals("")) {
            str = "AVISO: Instabilidade detectada e corrigida.";
            cor = Color.YELLOW.darker();
        } else if(frase.equals("") && porta == 0){
            str = "ERRO: " + erro;
            cor = Color.red;
        } else if(porta == 0 && erro.equals("")){
            str = "AVISO: " + frase;
            cor = Color.YELLOW.darker();
        } else if(frase.equals("") && erro.equals("")){
            str = "AVISO: problema detectado na porta " + porta;
            cor = Color.YELLOW.darker();
        } else if(frase.equals("")){
            str = "ERRO na porta " + porta + ": " + erro;
            cor = Color.red;
        } else if(porta == 0){
            str = frase + ": " + erro;
            cor = Color.YELLOW.darker();
        } else if(erro.equals("")){
            str = "AVISO na porta " + porta + ": " + frase;
            cor = Color.YELLOW.darker();
        } else{
            
        }
        addTexto(ChatTextPaneGeral, str, cor);
        addTexto(ChatTextPaneMaterial, str, cor);
    }

    synchronized private void listaClientes(JSONObject json) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                DefaultTableModel model = (DefaultTableModel) TabelaClients.getModel();
                model.setRowCount(0);
                ButtonGroup group = new ButtonGroup();
                JSONArray lista = json.getJSONArray("lista");
                for (int i = 0; i < lista.length(); i++) {
                    JSONObject usuarioJson = (JSONObject) lista.get(i);
                    if (!usuarioJson.has("descricao")) {
                        usuarioJson.put("descricao", "");
                    }
                    String tipo;
                    if (usuarioJson.get("tipo").equals("D")) {
                        tipo = "Doador";
                    } else {
                        tipo = "Coletor";
                    }
                    model.addRow(new Object[]{usuarioJson.get("porta"), usuarioJson.get("nome"), tipo, usuarioJson.get("material"), usuarioJson.get("descricao")});
                }
            }
        });

    }

    private void desconectaCliente(Socket socket) {
        ChatTextField.setEnabled(false);
        ChatSendBtn.setEnabled(false);
        ChatTextPaneMaterial.setText("");
        ChatPrivadoBtn.setEnabled(false);
        IpTextField.setEnabled(true);
        PortaTextField.setEnabled(true);
        NomeTextField.setEnabled(true);
        MaterialComboBox.setEnabled(true);
        ColetorRadioButton.setEnabled(true);
        DoadorRadioButton.setEnabled(true);
        if (DoadorRadioButton.isSelected()) {
            DescricaoTextPane.setEnabled(true);
        }
        JSONObject cliente = new JSONObject();
        //Preenche o objeto JSON com a action para desconectar
        cliente.put("action", "disconnect");
        String clienteDesconectandoJsonString = cliente.toString();

        //IPAddress = InetAddress.getLocalHost().getHostAddress(); //Pega o endereço
        //Manda mensagem ao servidor
        PrintStream saida;
        try {
            saida = new PrintStream(socket.getOutputStream());
            saida.println(clienteDesconectandoJsonString);//Envia uma String JSON
        } catch (IOException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChatPrivadoBtn;
    private javax.swing.JButton ChatSendBtn;
    private javax.swing.JTextField ChatTextField;
    private javax.swing.JTextPane ChatTextPaneGeral;
    private javax.swing.JTextPane ChatTextPaneMaterial;
    private javax.swing.JTextPane ChatTextPanePrivado;
    private javax.swing.JRadioButton ColetorRadioButton;
    private javax.swing.JButton ConectarButton;
    private javax.swing.JLabel DescricaoLabel;
    private javax.swing.JScrollPane DescricaoScrollPane;
    private javax.swing.JTextPane DescricaoTextPane;
    private javax.swing.JRadioButton DoadorRadioButton;
    private javax.swing.JLabel IpLabel;
    private javax.swing.JTextField IpTextField;
    private javax.swing.JComboBox<String> MaterialComboBox;
    private javax.swing.JLabel MaterialLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JLabel PortaLabel;
    private javax.swing.JTextField PortaTextField;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable TabelaClients;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
