/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaspkg;

import org.json.*;
import java.io.*;
import java.net.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import server.Usuario;

public class Inicio extends javax.swing.JFrame {

    public String jsao;
    public ArrayList<Usuario> clientes = new ArrayList<Usuario>();
    public Socket socketCliente;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        IpLabel = new javax.swing.JLabel();
        IpTextField = new javax.swing.JTextField();
        PortaTextField = new javax.swing.JTextField();
        NomeLabel = new javax.swing.JLabel();
        NomeTextField = new javax.swing.JTextField();
        MaterialLabel = new javax.swing.JLabel();
        MaterialComboBox = new javax.swing.JComboBox<>();
        DescricaoLabel = new javax.swing.JLabel();
        DescricaoScrollPane = new javax.swing.JScrollPane();
        DescricaoTextPane = new javax.swing.JTextPane();
        ConectarButton = new javax.swing.JButton();
        PortaLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ColetorRadioButton = new javax.swing.JRadioButton();
        DoadorRadioButton = new javax.swing.JRadioButton();
        jButtonDesconectar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IpLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IpLabel.setText("IP:");
        IpLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        IpLabel.setMaximumSize(new java.awt.Dimension(50, 15));
        IpLabel.setMinimumSize(new java.awt.Dimension(50, 15));
        IpLabel.setPreferredSize(new java.awt.Dimension(15, 15));
        jPanel3.add(IpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        IpTextField.setMaximumSize(new java.awt.Dimension(150, 20));
        IpTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        IpTextField.setPreferredSize(new java.awt.Dimension(150, 20));
        IpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(IpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, -1));

        PortaTextField.setMaximumSize(new java.awt.Dimension(50, 20));
        PortaTextField.setMinimumSize(new java.awt.Dimension(20, 20));
        PortaTextField.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel3.add(PortaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        NomeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NomeLabel.setText("Nome:");
        NomeLabel.setPreferredSize(new java.awt.Dimension(46, 15));
        jPanel3.add(NomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 20));
        jPanel3.add(NomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        MaterialLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaterialLabel.setText("Material:");
        jPanel3.add(MaterialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, 20));

        MaterialComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "oleo", "metal", "roupa", "papel", "plastico", "eletronico" }));
        MaterialComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(MaterialComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, -1));

        DescricaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DescricaoLabel.setText("Descrição:");
        jPanel3.add(DescricaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        DescricaoTextPane.setEnabled(false);
        DescricaoTextPane.setMinimumSize(new java.awt.Dimension(300, 200));
        DescricaoTextPane.setPreferredSize(new java.awt.Dimension(300, 200));
        DescricaoScrollPane.setViewportView(DescricaoTextPane);

        jPanel3.add(DescricaoScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 310, 260));

        ConectarButton.setText("Conectar");
        ConectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ConectarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, 20));

        PortaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PortaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PortaLabel.setText("Porta:");
        PortaLabel.setMaximumSize(new java.awt.Dimension(50, 15));
        PortaLabel.setMinimumSize(new java.awt.Dimension(50, 15));
        PortaLabel.setPreferredSize(new java.awt.Dimension(46, 15));
        jPanel3.add(PortaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        buttonGroup1.add(ColetorRadioButton);
        ColetorRadioButton.setText("Coletor");
        ColetorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColetorRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ColetorRadioButton);

        buttonGroup1.add(DoadorRadioButton);
        DoadorRadioButton.setText("Doador");
        DoadorRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DoadorRadioButtonStateChanged(evt);
            }
        });
        DoadorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoadorRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoadorRadioButton);

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 310, 60));

        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.setEnabled(false);
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 480, -1, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 510));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários Conectados"));
        jPanel5.setAutoscrolls(true);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Conversar");
        jButton2.setEnabled(false);
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Material", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 140));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 230));

        jButton1.setText("Enviar");
        jButton1.setEnabled(false);
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 20));

        jTextField1.setEnabled(false);
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 410, 20));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 490, 290));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 510, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarButtonActionPerformed
        JSONObject validacao = validaInsercao();
        if(validacao.getBoolean("success")){
            System.out.println("Tudo OK.");
        }else{
            JOptionPane.showMessageDialog(null, validacao.getString("message"), "ERRO", JOptionPane.WARNING_MESSAGE);
        }
        if (IpTextField.getText().trim().length() != 0 && PortaTextField.getText().trim().length() != 0) {
            System.out.println(IpTextField.getText());
            String ip = IpTextField.getText();
            int porta = Integer.parseInt(PortaTextField.getText());
            String nome = NomeTextField.getText();
            if (NomeTextField.getText().trim().length() != 0){
                String material = MaterialComboBox.getSelectedItem().toString();
                if (material != "Selecione...") {
                    String tipo = "";
                    String action = "connect";
                    if (DoadorRadioButton.isSelected() || ColetorRadioButton.isSelected()){
                         if (DoadorRadioButton.isSelected()) {
                        tipo = "D";
                    } else if (ColetorRadioButton.isSelected()){
                        tipo = "C";
                    }
                    String descricao = DescricaoTextPane.getText();
                    if (DoadorRadioButton.isSelected() && DescricaoTextPane.getText().trim().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Descrição não inserida. Por favor corrija!", "ERRO", JOptionPane.WARNING_MESSAGE);
                    }
                    else {
                        ConectarButton.setEnabled(false);
                        JSONObject json = new JSONObject();
                        json.put("action", action);
                        json.put("nome", nome);
                        json.put("material", material);
                        json.put("tipo", tipo);
                        if (DoadorRadioButton.isSelected()) {
                            json.put("descricao", descricao);
                        } else {
                            json.put("descricao", "Sem Descrição");
                        }
                        System.out.println(json);
                        jsao = json.toString();
                    
                    String serverHostname = new String(IpTextField.getText());
                    Integer porta1 = new Integer(PortaTextField.getText());
                    
                    System.out.println("Conectando ao IP " + serverHostname + " na porta " + porta1 + ".");
                    jButtonDesconectar.setEnabled(true);
                    Socket socket;
                    PrintStream out;
                    BufferedReader in;
                    
                    try {
                        socket = new Socket(serverHostname, porta1);
                        this.socketCliente = socket;
                        out = new PrintStream(socket.getOutputStream());
                        in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                        //JOptionPane.showConfirmDialog(null, "Conexao Realizada com Suceso!", "Desconectar", 0);
                        //Object[] option = {"OK", "Desconectar?"};
                        //int flag = JOptionPane.showOptionDialog(null, "Conexão Realizada com Sucesso!", "Conexão", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, null);
                        out.println(jsao);
                        BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));
                        //BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));
                        new Thread() {
                            
                            @Override
                            public void run() {
                                try {
                                    String userInput;
                                    while (((userInput = in.readLine()) != null) || socketCliente != null) {
                                        System.out.println("Entrou no while");
                                        try {
                                            JSONObject json = new JSONObject(userInput);
                                            iniciaAcao(json);
                                        } catch (JSONException ex) {
                                            System.out.println("Erro no json" + ex);
                                        }
                                        
                                        System.out.println("Saiu do while");
                                    }
                                    desconectaCliente(socket);
                                    out.close();
                                    in.close();
                                    socket.close();
                                    //stdIn.close();
                                    
                                } catch (IOException ex) {
                                    JOptionPane.showMessageDialog(null, "Servidou desconectou! " + serverHostname);
                                    jButtonDesconectar.setEnabled(false);
                                    ConectarButton.setEnabled(true);
                                    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                                    model.setRowCount(0);
                                    
                                }
                            }
                        }.start();
                        
                    } catch (UnknownHostException e) {
                        System.err.println();
                        JOptionPane.showMessageDialog(null, "Não é possível encontrar o servidor " + serverHostname);
                        System.exit(1);
                    } catch (IOException e) {
                        System.err.println("Não é possível conectar a " + serverHostname);
                        System.exit(1);
                    }
                    }
                    }else
                        JOptionPane.showMessageDialog(null, "Tipo de usuário não inserido. Por favor corrija!", "ERRO", JOptionPane.WARNING_MESSAGE);
                }else
                    JOptionPane.showMessageDialog(null, "Material não inserido. Por favor corrija!", "ERRO", JOptionPane.WARNING_MESSAGE);                    
            }else
                JOptionPane.showMessageDialog(null, "Nome não inserido. Por favor corrija!", "ERRO", JOptionPane.WARNING_MESSAGE);
        } else
            JOptionPane.showMessageDialog(null, "IP ou Porta não inseridos.", "ERRO", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_ConectarButtonActionPerformed

    private void DoadorRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DoadorRadioButtonStateChanged

    }//GEN-LAST:event_DoadorRadioButtonStateChanged

    private void DoadorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoadorRadioButtonActionPerformed
        if (DoadorRadioButton.isEnabled()) {
            DescricaoTextPane.setEnabled(true);
        }
    }//GEN-LAST:event_DoadorRadioButtonActionPerformed

    private void ColetorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColetorRadioButtonActionPerformed
        if (ColetorRadioButton.isEnabled()) {
            DescricaoTextPane.setText(null);
            DescricaoTextPane.setEnabled(false);
        }
    }//GEN-LAST:event_ColetorRadioButtonActionPerformed

    private void IpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpTextFieldActionPerformed

    private void MaterialComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialComboBoxActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        //JOptionPane.showConfirmDialog(null, "Desconectado com sucesso!", "Desconectado", JOptionPane.DEFAULT_OPTION);
        int opt = JOptionPane.OK_OPTION;
        Object[] options = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, "Você deseja se desconectar?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcao == JOptionPane.NO_OPTION) {
            opt = JOptionPane.NO_OPTION;
        }
        int opcao1 = JOptionPane.showOptionDialog(null, "Tem certeza?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if (opcao1 == opt) {
            desconectaCliente(socketCliente);
            socketCliente = null;
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            ConectarButton.setEnabled(true);
            jButtonDesconectar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });

    }
    
    private JSONObject validaInsercao(){
        String message = "";
        JSONObject validacao = new JSONObject();
        validacao.put("success", true);
        if(IpTextField.getText().trim().length() == 0){
            message += "O Campo IP é Obrigatório.\n";
            validacao.put("success", false);
        }
        if(PortaTextField.getText().trim().length() == 0){
            message += "O Campo Porta é Obrigatório.\n";
            validacao.put("success", false);
        }
        
        if(NomeTextField.getText().trim().length() == 0){
            message += "O Campo Nome é Obrigatório.\n";
            validacao.put("success", false);
        }
        
        if(MaterialComboBox.getSelectedItem().toString() == "Selecione..."){
            message += "É obrigatório selecionar um material.\n";
            validacao.put("success", false);
        }
        
        if(!DoadorRadioButton.isSelected() && !ColetorRadioButton.isSelected()){
            message += "É obrigatório selecionar um tipo.\n";
            validacao.put("success", false);
        }
        
        validacao.put("message", message);
        return validacao;
    }

    private void iniciaAcao(JSONObject json) {
        System.out.println("Verificando ação...");
        if (json.has("action")) {
            if (json.get("action").equals("client_list")) {
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                ButtonGroup group = new ButtonGroup();
                JSONArray lista = json.getJSONArray("lista");
                for (int i = 0; i < lista.length(); i++) {
                    JSONObject usuarioJson = (JSONObject) lista.get(i);
                    System.out.println(usuarioJson);
                    model.addRow(new Object[]{usuarioJson.get("porta"), usuarioJson.get("nome"), usuarioJson.get("tipo"), usuarioJson.get("material"), usuarioJson.get("descricao")});
                }
            } else {
                System.out.println("A ação " + json.get("action") + " não existe.");
            }
        } else {
            System.out.println("Action não encontrada.");
        }
    }

    private void desconectaCliente(Socket socket) {
        JSONObject cliente = new JSONObject();
        //Preenche o objeto JSON com a action para desconectar
        cliente.put("action", "disconnect");
        String clienteDesconectandoJsonString = cliente.toString();

        //IPAddress = InetAddress.getLocalHost().getHostAddress(); //Pega o endereço
        //Manda mensagem ao servidor
        PrintStream saida;
        try {
            saida = new PrintStream(socket.getOutputStream());
            System.out.println("DESCONECTADO DO SERVIDOR: " + clienteDesconectandoJsonString);
            saida.println(clienteDesconectandoJsonString);//Envia uma String JSON
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ColetorRadioButton;
    private javax.swing.JButton ConectarButton;
    private javax.swing.JLabel DescricaoLabel;
    private javax.swing.JScrollPane DescricaoScrollPane;
    private javax.swing.JTextPane DescricaoTextPane;
    private javax.swing.JRadioButton DoadorRadioButton;
    private javax.swing.JLabel IpLabel;
    private javax.swing.JTextField IpTextField;
    private javax.swing.JComboBox<String> MaterialComboBox;
    private javax.swing.JLabel MaterialLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JLabel PortaLabel;
    private javax.swing.JTextField PortaTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
